import 'package:islam200qa/utils/string_utils.dart';
import 'package:islam200qa/widgets/index/index_multi_sections_model.dart';
import 'package:islam200qa/widgets/index/index_section_model.dart';
import 'package:islam200qa/widgets/index/index_sections_combiner_model.dart';
import 'package:islam200qa/widgets/index/index_single_section_model.dart';

const int lastSection = 212;

const double indexBasePadding = 8.0;

List<IndexSectionModel> index = [
  const IndexSingleSectionModel(
    sectionId: 1,
  ),
  IndexMultiSectionsModel(
    title: 'أول ما يجب على الانسان والغاية من وجوده',
    startSection: 2,
    endSection: 11,
  ),
  const IndexSingleSectionModel(
    sectionId: 12,
  ),
  IndexSectionsCombinerModel(
    title: 'مراتب الدين',
    children: [
      const IndexSingleSectionModel(
        sectionId: 13,
      ),
      IndexMultiSectionsModel(
        title: 'الإسلام وأدله',
        startSection: 14,
        endSection: 35,
      ),
      IndexSectionsCombinerModel(
        title: 'الإيمان وأدلته',
        children: [
          const IndexSingleSectionModel(
            sectionId: 36,
          ),
          IndexMultiSectionsModel(
            title: 'الإيمان قول وعمل',
            startSection: 37,
            endSection: 42,
          ),
          IndexSectionsCombinerModel(
            title: 'الإيمان بالله وأقسامه الثلاثة',
            children: [
              const IndexSingleSectionModel(
                sectionId: 43,
              ),
              IndexMultiSectionsModel(
                title: 'توحيد الألوهية وضده الشرك',
                startSection: 44,
                endSection: 47,
              ),
              IndexMultiSectionsModel(
                title: 'توحيد الربوبية وضده الكفر',
                startSection: 48,
                endSection: 49,
              ),
              IndexMultiSectionsModel(
                title: 'توحيد الأسماء والصفات وأدلته وبيان بعض ما اختلف فيه في هذا الباب',
                startSection: 50,
                endSection: 70,
              ),
              const IndexSingleSectionModel(
                sectionId: 71,
              ),
            ],
          ),
          IndexMultiSectionsModel(
            title: 'الإيمان بالملائكة',
            startSection: 72,
            endSection: 74,
          ),
          IndexMultiSectionsModel(
            title: 'الإيمان بالكتب',
            startSection: 75,
            endSection: 84,
          ),
          IndexMultiSectionsModel(
            title: 'الإيمان بالرسل',
            startSection: 85,
            endSection: 98,
          ),
          IndexSectionsCombinerModel(
            title: 'الإيمان باليوم الآخر',
            children: [
              const IndexSingleSectionModel(
                sectionId: 99,
              ),
              const IndexSingleSectionModel(
                sectionId: 100,
              ),
              const IndexSingleSectionModel(
                sectionId: 101,
              ),
              IndexMultiSectionsModel(
                title: 'بعض أمارات اليوم الآخر',
                startSection: 102,
                endSection: 103,
              ),
              const IndexSingleSectionModel(
                sectionId: 104,
              ),
              IndexMultiSectionsModel(
                title: 'فتنة القبر ونعيمه أو عذابه',
                startSection: 105,
                endSection: 106,
              ),
              IndexMultiSectionsModel(
                title: 'البعث والنفخ',
                startSection: 107,
                endSection: 109,
              ),
              IndexMultiSectionsModel(
                title: 'الحشر',
                startSection: 110,
                endSection: 113,
              ),
              IndexMultiSectionsModel(
                title: 'العرض والحساب ونشر الصحف',
                startSection: 114,
                endSection: 117,
              ),
              IndexMultiSectionsModel(
                title: 'الميزان وبيان وصفه',
                startSection: 118,
                endSection: 119,
              ),
              IndexMultiSectionsModel(
                title: 'الصراط',
                startSection: 120,
                endSection: 121,
              ),
              IndexMultiSectionsModel(
                title: 'القصاص وصفته',
                startSection: 122,
                endSection: 123,
              ),
              IndexMultiSectionsModel(
                title: 'الحوض وصفته',
                startSection: 124,
                endSection: 125,
              ),
              IndexMultiSectionsModel(
                title: 'الجنة والنار ووصفهما وبعض الشبه المتعلقة بهما',
                startSection: 126,
                endSection: 129,
              ),
              const IndexSingleSectionModel(
                sectionId: 130,
              ),
              IndexMultiSectionsModel(
                title: 'الشفاعة وأنواعها',
                startSection: 131,
                endSection: 132,
              ),
              const IndexSingleSectionModel(
                sectionId: 133,
              ),
            ],
          ),
          IndexSectionsCombinerModel(
            title: 'الإيمان بالقدر',
            children: [
              const IndexSingleSectionModel(
                sectionId: 134,
              ),
              const IndexSingleSectionModel(
                sectionId: 135,
              ),
              IndexMultiSectionsModel(
                title: 'المرتبة الأولى: الإيمان بالعلم',
                startSection: 136,
                endSection: 136,
              ),
              IndexMultiSectionsModel(
                title: 'المرتبة الثانية: الإيمان بالكتابة وبيان أنواعها',
                startSection: 137,
                endSection: 143,
              ),
              IndexMultiSectionsModel(
                title: 'المرتبة الثالثة: الإيمان بالمشيئة',
                startSection: 144,
                endSection: 145,
              ),
              IndexMultiSectionsModel(
                title: 'المرتبة الرابعة: الإيمان بالخلق',
                startSection: 146,
                endSection: 146,
              ),
              IndexMultiSectionsModel(
                title: 'بعض الشبهات المتعلقة بباب القدر',
                startSection: 147,
                endSection: 150,
              ),
            ],
          ),
          const IndexSingleSectionModel(
            sectionId: 151,
          ),
        ],
      ),
      IndexMultiSectionsModel(
        title: 'الإحسان وأدلته',
        startSection: 152,
        endSection: 152,
      ),
    ],
  ),
  IndexSectionsCombinerModel(
    title: 'الكفر وأنواعه',
    children: [
      const IndexSingleSectionModel(
        sectionId: 153,
      ),
      const IndexSingleSectionModel(
        sectionId: 154,
      ),
      IndexMultiSectionsModel(
        title: 'الكفر الأكبر وأقسامه',
        startSection: 155,
        endSection: 157,
      ),
      const IndexSingleSectionModel(
        sectionId: 158,
      ),
      const IndexSingleSectionModel(
        sectionId: 159,
      ),
      IndexMultiSectionsModel(
        title: 'أقسام الظلم والفسوق والنفاق',
        startSection: 160,
        endSection: 163,
      ),
      IndexMultiSectionsModel(
        title: 'من أشكال الكفر: حكم السحر والساحر',
        startSection: 164,
        endSection: 166,
      ),
      IndexMultiSectionsModel(
        title: 'الرقى المشروعة  والرقى الممنوعة',
        startSection: 167,
        endSection: 168,
      ),
      IndexMultiSectionsModel(
        title: 'حكم التعاليق والتمائم',
        startSection: 169,
        endSection: 170,
      ),
      IndexMultiSectionsModel(
        title: 'حكم الكهان والمنجمين',
        startSection: 171,
        endSection: 174,
      ),
      const IndexSingleSectionModel(
        sectionId: 175,
      ),
      const IndexSingleSectionModel(
        sectionId: 176,
      ),
    ],
  ),
  IndexSectionsCombinerModel(
    title: 'أقسام المعاصي وبم تكفر السيئات',
    children: [
      const IndexSingleSectionModel(
        sectionId: 177,
      ),
      const IndexSingleSectionModel(
        sectionId: 178,
      ),
      IndexMultiSectionsModel(
        title: 'التوبة النصوح',
        startSection: 179,
        endSection: 185,
      ),
    ],
  ),
  IndexSectionsCombinerModel(
    title: 'الصراط المستقيم الذي أمرنا الله تعالى بسلوكه',
    children: [
      IndexMultiSectionsModel(
        title: 'السنّة',
        startSection: 186,
        endSection: 188,
      ),
      IndexMultiSectionsModel(
        title: 'البدع وأنواعها',
        startSection: 189,
        endSection: 195,
      ),
    ],
  ),
  IndexMultiSectionsModel(
    title: 'الواجب التزامه في أصحاب الرسول صلى الله عليه وسلم وأهل بيته',
    startSection: 196,
    endSection: 206,
  ),
  const IndexSingleSectionModel(
    sectionId: 207,
  ),
  const IndexSingleSectionModel(
    sectionId: 208,
  ),
  const IndexSingleSectionModel(
    sectionId: 209,
  ),
  const IndexSingleSectionModel(
    sectionId: 210,
  ),
  const IndexSingleSectionModel(
    sectionId: 211,
  ),
  const IndexSingleSectionModel(
    sectionId: 212,
  ),
];

const List<String> indexTitles = [
  '',
  'المقدمة',
  'أول ما يجب على العباد',
  'الأمر الذي خلق الله الخلق لأجله',
  'معنى العبد',
  'تعريف العبادة',
  'متى يكون العمل عبادة',
  'علامة محبة العبد ربه عز وجل',
  'بماذا عرف العباد ما يحبه الله ويرضاه',
  'شروط العبادة',
  'صدق العزيمة',
  'معنى إخلاص النية',
  'الشَّرع الذي أمر اللهُ تعالى أن لا يُدان إلا به',
  'مراتب دين الإسلام',
  'معنى الإسلام',
  'الدليل على شموله الدين كله عند الإطلاق',
  'الدليل على تعريف الدين بالأركان الخمسة عند التفصيل',
  'محلُّ الشهادتين من الدّين',
  'دليل شهادة أن لا إله إلا الله',
  'معنى شهادة أن لا إله إلا الله',
  'شروط شهادة أن لا إله إلا الله',
  'دليل اشتراط العلم من الكتاب والسنة',
  'دليل اشتراط اليقين من الكتاب والسنة',
  'دليل اشتراط الانقياد من الكتاب والسنة',
  'دليل اشتراط القبول من الكتاب والسنة',
  'دليل الصدق من الكتاب والسنة',
  'دليل اشتراط المحبة من الكتاب والسنة',
  'دليل الموالاة لله والمعاداة لأجله',
  'دليل شهادة أن محمدا رسول الله صلى الله عليه وسلم',
  'معنى شهادة أن محمدا رسول الله صلى الله عليه وسلم',
  'شروط شهادة أن محمدا رسول الله صلى الله عليه وسلم',
  'دليل الصلاة والزكاة',
  'دليل الصوم',
  'دليل الحج',
  'حكم من جحد واحدا من قواعد الإسلام الخمس أو أقر به واستكبر عنه',
  'حكم من أقر بها ثم تركها لنوع تكاسل أو تأويل',
  'تعريف الإيمان',
  'الدليل على أن الإيمان قول وعمل',
  'الدليل على زيادة الإيمان ونقصانه',
  'الدليل على تفاضل أهل الإيمان فيه',
  'الدليل على أن الإيمان يشمل الدين كله عند الإطلاق',
  'الدليل على تعريف الإيمان بالأركان الستة عند التفصيل من السنة والكتاب',
  'معنى الإيمان بالله عز وجل',
  'توحيد الإلهية',
  'ما يضاد توحيد الإلهية',
  'الشرك الأكبر',
  'الشرك الأصغر',
  'الفرق بين الواو وثم',
  'توحيد الربوبية',
  'ما يضاد توحيد الربوبية',
  'توحيد الأسماء والصفات',
  'دليل الأسماء الحسنى من الكتاب والسنة',
  'مثال الأسماء الحسنى من القرآن',
  'مثال الأسماء الحسنى من السنة',
  'دلالة الأسماء الحسنى وأمثلتها',
  'أقسام دلالة الأسماء الحسنى من جهة التضمن',
  'أقسام الأسماء الحسنى من جهة إطلاقها على الله عز وجل',
  'مثال لصفات الذات من الكتاب',
  'مثال لصفات الذات من السنة',
  'مثال لصفات الأفعال من الكتاب',
  'مثال لصفات الأفعال من السنة',
  'أسماء الله تعالى كلها توقيفية',
  'ما يتضمنه اسمه العلي الأعلى وما في معناه',
  'دليل علو الفوقية من الكتاب',
  'دليل علو الفوقية من السنة',
  'أقوال أئمة السلف الصالح في مسألة الاستواء',
  'دليل علو القهر من الكتاب',
  'دليل علو القهر من السنة',
  'دليل علو الشأن',
  'معنى قوله عليه السلام في الأسماء الحسنى من أحصاها دخل الجنة',
  'ما يضاد توحيد الأسماء والصفات',
  'جميع أنواع التوحيد متلازمة',
  'الدليل على الإيمان بالملائكة من الكتاب والسنة',
  'معنى الإيمان بالملائكة',
  'بعض أنواع الملائكة',
  'دليل الإيمان بالكتب',
  'تسمية الكتب في القرآن',
  'معنى الإيمان بكتب الله عز وجل',
  'منزلة القرآن من الكتب المتقدمة',
  'ما يجب التزامه في حق القرآن على جميع الأمة',
  'معنى التمسك بالكتاب والقيام بحقه',
  'حكم من قال بخلق القرآن',
  'صفة الكلام ذاتية أو فعلية',
  'التعريف بالواقفة وبيان حكمهم',
  'حكم من قال لفظي بالقرآن مخلوق',
  'دليل الإيمان بالرسل',
  'معنى الإيمان بالرسل',
  'اتفقت دعوة الرسل على أصل العبادة وأساسها',
  'الدليل على اتفاق الرسل في أصل العبادة',
  'الدليل على اختلاف شرائع الرسل في الفروع',
  'هل قص الله جميع الرسل في القرآن',
  'جملة الرسل الذين سماهم الله في القرآن',
  'أُولو العزم من الرسل',
  'أول الرسل',
  'متى كان الاختلاف',
  'خاتم النبيين والدليل على ذلك',
  'خصائص النبي صلى الله عليه وسلم',
  'معجزات الأنبياء',
  'دليل إعجاز القرآن الكريم',
  'دليل الإيمان باليوم الآخر',
  'معنى الإيمان باليوم الآخر',
  'متى تكون الساعة',
  'مثال أمارات الساعة من الكتاب',
  'مثال أمارات الساعة من السنة',
  'دليل الإيمان بالموت',
  'دليل فتنة القبر ونعيمه أو عذابه من الكتاب',
  'دليل فتنة القبر ونعيمه أو عذابه من السنة',
  'دليل البعث من القبور',
  'حكم من كذب البعث',
  'دليل النفخ في الصور وكم نفخات ينفخ فيه',
  'صفة الحشر من الكتاب',
  'صفة الحشر من السنة',
  'صفة الموقف من الكتاب',
  'صفة الموقف من السنة',
  'صفة العرض والحساب من الكتاب',
  'صفة العرض والحساب من السنة',
  'صفة نشر الصحف من الكتاب',
  'دليل نشر الصحف من السنة',
  'دليل الميزان من الكتاب وبيان صفة الوزن',
  'دليل الميزان من السنة وبيان صفة الوزن',
  'دليل الصراط من الكتاب',
  'دليل الصراط من السنة',
  'دليل القصاص من الكتاب',
  'دليل القصاص وصفته من السنة',
  'دليل الحوض من الكتاب',
  'دليل الحوض وصفته من السنة',
  'دليل الإيمان بالجنة والنار',
  'معنى الإيمان بالجنة والنار',
  'الدليل على وجود الجنة والنار الآن',
  'الدليل على بقاء الجنة والنار وأنهما لا يفنيان',
  'الدليل على أن المؤمنين يرون ربهم تبارك وتعالى في الدار الآخرة',
  'دليل الإيمان بالشفاعة وممن تكون ولمن تكون',
  'أنواع الشفاعة الست وأعظمها',
  'معنى حديث لن يُدخل الجنة أحد عمله والجمع بينه وبين آية وَنُودُوا أَنْ تِلْكُمُ الْجَنَّةُ أُورِثْتُمُوهَا بِمَا كُنْتُمْ تَعْمَلُون',
  'دليل الإيمان بالقدر جملة',
  'مراتب الإيمان بالقدر',
  'دليل المرتبة الأولى الإيمان بالعلم',
  'دليل المرتبة الثانية الإيمان بكتابة المقادير وما يدخلها من التقادير',
  'دليل التقدير الأزلي',
  'دليل التقدير العمري يوم الميثاق',
  'دليل التقدير العمري الذي عند أول تخليق النطفة',
  'دليل التقدير الحولي في ليلة القدر',
  'دليل التقدير اليومي',
  'ما يقتضيه سبق المقادير بالشقاوة والسعادة',
  'دليل المرتبة الثالثة وهي الإيمان بالمشيئة',
  'الإرادة في النصوص جاءت على معنيين',
  'دليل المرتبة الرابعة من الإيمان بالقدر وهي مرتبة الخلق',
  'معنى قول النبي عليه السلام والخير كله في يديك والشر ليس إليك',
  'للعباد قدرة على أعمالهم ولهم مشيئة وإرادة',
  'أليس ممكنا في قدرة الله أن يجعل كل عباده مؤمنين',
  'منزلة الإيمان بالقدر من الدين',
  'شعب الإيمان',
  'دليل الإحسان من الكتاب والسنة',
  'ما يضاد الإيمان',
  'كيفية منافاة الكفر الاعتقادي للإيمان بالكلية',
  'أقسام الكفر الأكبر المخرج من الملة',
  'كفر الجهل والتكذيب',
  'كفر النفاق',
  'الكفر العملي الذي لا يخرج من الملة',
  'السجود للصنم والاستهانة بالكتاب وسب الرسول والهزل بالدين',
  'أقسام الظلم والفسوق والنفاق',
  'مثال كل من الظلم الأكبر والأصغر',
  'مثال الفسوق الأكبر والأصغر',
  'مثال النفاق الأكبر والأصغر',
  'حكم السحر والساحر',
  'حد الساحر',
  'تعريف النشرة وبيان حكمها',
  'الرقى المشروعة',
  'الرقى الممنوعة',
  'حكم التعاليق من التمائم والأوتار والحلق والخيوط والودع ونحوها',
  'حكم التعاليق من القرآن',
  'حكم الكهان',
  'حكم من صدق كاهنا',
  'حكم التَّنْجيم',
  'حكم الاستسقاء بالأنواء',
  'حكم الطِّيَرَة وما يُذْهِبُها',
  'حكم العين',
  'أقسام المعاصي وبماذا تكفر السيئات',
  'تعريف الكبائر',
  'ما تكفر به جميع الصغائر والكبائر',
  'التوبة النصوح',
  'وقت انقطاع التوبة في حق كل فرد من أفراد الناس',
  'انقطاع التوبة من عمر الدنيا',
  'حكم من مات من الموحدين مُصِرَّا على كبيرة',
  'هل الحدود كفارات لأهلها',
  'الجمع بين قوله عليه السلام فهو إلى الله إن شاء عفا عنه وإن شاء عاقبه وبين أن من رجحت سيئاته بحسناته دخل النار',
  'المراد بالصراط المستقيم الذي أمرنا الله تعالى بسلوكه',
  'الصراط المستقيم كيفية سلوكه والسلامة من الانحراف عنه',
  'ما يضاد السنة',
  'أقسام البدعة باعتبار إخلالها بالدين',
  'البدع المكفرة',
  'البدع الغير مكفرة',
  'أقسام البدع بحسب ما تقع فيه',
  'أقسام البدع في العبادات',
  'حالات البدعة مع العبادة التي تقع فيها',
  'البدع في المعاملات',
  'الواجب التزامه في أصحاب رسول الله صلى الله عليه وسلم وأهل بيته',
  'أفضل الصحابة إجمالا',
  'أفضل الصحابة تفصيلا',
  'مدة الخلافة بعد رسول الله صلى الله عليه وسلم',
  'الدليل على خلافة الأربعة جملة',
  'الدليل على خلافة الثلاثة إجمالا',
  'الدليل على خلافة أبي بكر وعمر رضي الله عنهما إجمالا',
  'الدليل على خلافة أبي بكر وتقديمه فيها',
  'الدليل على تقديم عمر في الخلافة بعد أبي بكر',
  'الدليل على تقديم عثمان بعدهما في الخلافة',
  'الدليل على خلافة علي وأولويته بالحق بعدهم',
  'الواجب لولاة الأمور والدليل على ذلك',
  'على من يجب الأمر بالمعروف والنهي عن المنكر وما مراتبه',
  'حكم كرامات الأولياء',
  'صفة أولياء الله',
  'الطائفة التي عناها النبي عليه السلام بقوله لا تزال طائفة من أمتي على الحق ظاهرة',
  'الخاتمة',
];

final List<String> indexTitlesProcessed = indexTitles.map(normalizeArabicText).toList();
